### PR TITLE
YOLO supports grayscale(1 channel) image

### PR DESCRIPTION
**Pull request by thomaspark-pkj**
YOLO supports grayscale(1 channel) image

### CODE REVIEW

**Comment by Grabber** [comment]
@thomaspark-pkj,

Your implementation seems to be good, but there is still something missing. Have you tried to train a network on CPU or GPU?

./darknet yolo train NETWORK.cfg is failing, giving:
```
CUDA Error: __global__ function call is not configured
darknet: ./src/cuda.c:35: check_error: Assertion `0' failed.
Aborted (core dumped)
```

And the gdb backtrace is:
```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1edd267c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f1edd267c37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f1edd26b028 in __GI_abort () at abort.c:89
#2  0x00007f1edd260bf6 in __assert_fail_base (
    fmt=0x7f1edd3b13b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x48c5c1 "0", file=file@entry=0x48aa10 "./src/cuda.c",
    line=line@entry=35,
    function=function@entry=0x48aa54 <__PRETTY_FUNCTION__.10617> "check_error") at assert.c:92
#3  0x00007f1edd260ca2 in __GI___assert_fail (assertion=0x48c5c1 "0",
    file=0x48aa10 "./src/cuda.c", line=35,
    function=0x48aa54 <__PRETTY_FUNCTION__.10617> "check_error") at assert.c:101
#4  0x0000000000402ea3 in check_error.part ()
#5  0x000000000040aa39 in check_error ()
#6  0x000000000040669c in gemm_ongpu ()
#7  0x000000000043ff1a in forward_connected_layer_gpu ()
#8  0x0000000000488454 in forward_backward_network_gpu(network, float*, float*) ()
#9  0x000000000048862f in train_network_datum_gpu ()
#10 0x000000000043d10a in train_network ()
#11 0x00000000004557db in train_yolo ()
#12 0x0000000000403255 in main ()
```

**Comment by thomaspark-pkj** [comment]
Thank you for comment. But it works fine here. Could you show me the NETWORK.cfg file?
And could you check below link?
http://stackoverflow.com/questions/37851098/darknet-framework-fails-to-start-with-gpu-acceleration-using-cuda
I saw error same as you before. I solved the problem by changing 'ARCH' parameter in Makefile.
(I changed 'compute_52' to 'compute_30' at GTX 960M, but default value works at GTX 1080)

**Comment by Grabber** [comment]
@thomaspark-pkj 

That is not a problem in my setup, I have been training networks for months... on different GPUs. 
What network are you using?

**Comment by Grabber** [comment]
@thomaspark-pkj, yolo-small.cfg, yolo-coco.cfg, yolo.cfg, tiny-yolo.cfg are unstable... it start training than freezes, very strange.

The traceback I sent you is from a model I was testing, with different layers combinations.

**Comment by thomaspark-pkj** [comment]
@Grabber 
I only changed 'channels=3' to 'channels=1' in yolo.train.cfg and tiny-yolo.cfg.
I will check again.

**Comment by Grabber** [comment]
@thomaspark-pkj 

Could you please try this network.cfg?

```
[net]
batch=64
subdivisions=2
height=227
width=227
channels=1
momentum=0.9
decay=0.0005
learning_rate=0.0001
policy=steps
steps=20,40,60,80,20000,30000
scales=5,5,2,2,.1,.1
max_batches=50000

[crop]
crop_width=227
crop_height=227
flip=0
angle=0
saturation=1.5
exposure=1.5

[convolutional]
filters=4
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
filters=8
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
filters=16
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=4
stride=4

[convolutional]
filters=32
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[convolutional]
filters=64
size=3
stride=1
pad=1
activation=leaky

[maxpool]
size=2
stride=2

[connected]
output=256
activation=linear

[connected]
output=4096
activation=leaky

[dropout]
probability=.5

[connected]
output=539
activation=linear

[detection]
classes=1
coords=4
rescore=1
side=7
num=2
softmax=0
sqrt=1
jitter=.2

object_scale=1
noobject_scale=.5
class_scale=1
coord_scale=5
```

**Comment by thomaspark-pkj** [comment]
@Grabber 
I got a same error as you. I will try to fix it.

**Comment by thomaspark-pkj** [comment]
The reason is 'crop layer'. yolo.train.cfg and tiny-yolo.cfg do not have crop layer. So I didn't check it.
After fixing the problem, I will send pull request again.

**Comment by Grabber** [comment]
@thomaspark-pkj, you are right... it is training if I remove crop layer.

**Comment by Grabber** [comment]
@thomaspark-pkj, we also have to review detection mode... it is seg. faulting too.

**Comment by thomaspark-pkj** [comment]
How I test detection mode? I only applied code and tested related to YOLO. (refered YOLO website)

**Comment by Grabber** [comment]
@thomaspark-pkj, are you on-line on Hangouts or Skype? Send me a message grabber@gmail.com or grabberbr

**Comment by thomaspark-pkj** [comment]
I fixed it. Do not convert to hsv when image is 1 channel.

**Comment by ailias** [comment]
I am curious about how to choose the B bounding boxes x,y,w,h for each cell ?  I guess it is randomly initialized and optimized with SGD, but I am not sure.

**Pull request closed without merging**
