### PR TITLE
Going full C++. Never go full C++

### PR DESCRIPTION
**Pull request by kunaltyagi**
Went full C++ in order to get this working with OpenCV4

Also a few changes in order to get it working with [darknet_ros](https://github.com/leggedrobotics/darknet_ros)

Please recommend changes since I've mowed the code quite haphazardly

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Made an error in mat to image conversions.

**Comment by cenit** [comment]
did you check the Alexey fork? github.com/alexeyab/darknet
it works very well with opencv2/3/4 :)

**Comment by kunaltyagi** [comment]
Thanks for that :)

**Comment by elgalu** [comment]
https://github.com/AlexeyAB/darknet

**Pull request closed without merging**
