### PR TITLE
Some modification to finetune the yolov3.

### PR DESCRIPTION
**Pull request by khanh1412**
Hi @pjreddie,
I have made some changes in darknet code to train only the last layer on other dataset.
Here it is.

modified:   include/darknet.h : add member "trainable" to struct layer (specify which layer to train)
new file:   python/darknet3.py : python3 ver for python.py
new file:   scripts/makelist.py : a small scipt to create train images list (when bash script can't because of exceeding variables list)
modified:   src/network.c : add 1 condition when updating weights. I don't know whether it's ok.
modified:   src/parser.c : add parser for "trainable"

...
It may conflicts with the old cfg file.
Any idea to make it compatible?
Thanks

### CODE REVIEW

**Comment by saivineethkumar** [comment]
Hi @khanh1412 
can you explain a little more in detail about what these changes are for? I didn't exactly understood what these changes will do.

And actually I am looking for something where in classification task using Vgg/ resnet, we can extend the last layer from 1000 to something like 1005 ( that is to add more classes) and still import the pre-trained weights for this layer where all the new connections will have random weights and the old ones will have weights from the pre-trained network. so that I can train the network with images of new classes and not the whole imagenet data from scratch. Is this what your changes to the code do?

thanks!

**Comment by khanh1412** [comment]
@saivineethkumar Actually, I have missed some changes in parser.c.
The weights in darknet are compressed as binary files so it needs some trick to extract the correct part for each layer.
To answer your question,
The darknet code is already has the "stopbackward" variable to specify which layer to stop doing back propagation. It works only for yolov2 and classification networks because of they have only 1 detection layers. (3 in yolov3 and 2 in yolov3-tiny).
So, to deal with yolov3, I added a variable named "trainable" (inspired by tensorflow). When training, the layer only be updated if the trainable=1 is specified in cfg file.
That's similar to tensorflow when you can specify which variable to train.
Take a look at line parser.c : 1149. 
function "void load_convolutional_weights", it loads weights for layer " from file stream fp.
For example, in yolov3, at the 1st detection layer, the previous layer is 81. 2 things are compressed in weights file is l.biases and l.weights. length of biases is 255, length of weights is 255*256. What you can do is take them from file stream and put to l.weights and l.biases depends on what you doing.
After doing that, you should probably extract the weights out to a ".weights" file. and use it as normal.

Good luck further, probably, i wouldn't read about this code anymore.

**Comment by saivineethkumar** [comment]
thanks @khanh1412 

I am unable to figure out the values of `l.inputs` and `l.outputs` for a layer `l` . what do they signify in the network?
And for each layer we only have 1 bias right? but in code we load `l.outputs` number of values for biases. why is that so?

I think these are little things but I cant figure it out from the script.
I tried printing these values by editing the script ` parser.c` but it is not printing the values, it is not at all reflecting any changes made to the script `parser.c`. I am not sure why is that happening.

**Comment by khanh1412** [comment]
@saivineethkumar 
1. Probably, `l.inputs` and `l.outouts` are numbers of elements in input array and output array for each layer. I used `git grep -n l\.inputs`
2. Can you specify which line of code?
3. Possible. Think that all files in `src` are darknet library and in `examples` are how to use darknet library.
4. Probably `make clean` and `make`

**Comment by saivineethkumar** [comment]
@khanh1412 


> Can you specify which line of code?

first line in the function `load_connected_weights `  in `parser.c` file that is 
`fread(l.biases, sizeof(float), l.outputs, fp); ` 
In the above line we are loading `l.outputs` number of values right? 



 And I didn't get this point. 
> Possible. Think that all files in src are darknet library and in examples are how to use darknet library.

**Comment by khanh1412** [comment]
That reads `(l.outputs)*sizeof(float)` bytes from file stream fp. You can search the `fread` on google

**Comment by saivineethkumar** [comment]
oh! I thought l.output number of float values are loaded from file, sorry my bad! 
so we are just loading one value for bias for a layer l then.

and what do you mean by this line

> Possible. Think that all files in src are darknet library and in examples are how to use darknet library.



thanks for the help!

**Comment by khanh1412** [comment]
@saivineethkumar 
Let's read from `examples/darknet.c` this file creates an interaction for user to use some functions like `./darknet detector test cfg/coco.data ...`. If you want to build your own model, just copy `src` `include` and write your own `Makefile`. I have learnt C recently, so maybe i used some wrong terminologies.

**Comment by saivineethkumar** [comment]
@khanh1412 
thanks for the help man! You cleared a lot of doubts :)

**Comment by Fab16BSB** [comment]
@khanhhhh do you have any news about transfert learning yolov3
I tried your code and i have many questions : 
Concerning the class file (.names) what i need to put on ? (all class + new class or juste new class)

what about anchor ? Do you think i need to generate new anchors on new class or generate it on new class + old class or take the original anchors

**Pull request closed without merging**
