### PR TITLE
refactoring network.c to use more performant switch statement instead…

### PR DESCRIPTION
**Pull request by willricketts**
… of huge conditional chain

### CODE REVIEW

**Comment by Grabber** [comment]
@willricketts can you provide some time analysis to prove that is running faster?

**Comment by pvtmert** [comment]
i can provide these:

http://stackoverflow.com/questions/2158759/case-vs-if-else-if-which-is-more-efficient
http://stackoverflow.com/questions/449273/why-the-switch-statement-and-not-if-else

**Comment by willricketts** [comment]
@pvtmert precisely the examples I would have provided. Cheers! 👍

**Comment by beru** [comment]
@willricketts This PR should be closed. A function pointer is used now in the `forward_network` function.

**Comment by pjreddie** [comment]
But it's so performant! with it's switch statement! I say we leave it open for posterity.

**Comment by beru** [comment]
Oh OK. If you say so... this is fine. :neutral_face: :coffee:

**Pull request closed without merging**
